language: java
sudo: required
dist: xenial

jdk:
  - openjdk8
  - oraclejdk8
  - openjdk9
  - oraclejdk9
  - oraclejdk11

branches:
  except:
    - /^v|d\d+\.\d+\.\d+$/
    - /^jenkins-veraPDF-plugins-v|d\\d+\\.\\d+\\.\\d+$/
