language: java
sudo: required
dist: trusty

jdk:
  - openjdk7
  - openjdk8
  - oraclejdk7
  - oraclejdk8

branches:
  except:
    - /^v|d\d+\.\d+\.\d+$/
    - /^jenkins-veraPDF-plugins-v|d\\d+\\.\\d+\\.\\d+$/
