language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"

before_install:
  - sudo -H pip install pyinstaller

install:
  - dpkg-buildpackage -tc -uc -us

script:
  - python -m unittest discover

after_success:
  - sudo dpkg -i ../jpylyzer_1.10.1_amd64.deb
  - jpylyzer --version
